const STATES = {
    MAIN_MENU: 'MAIN_MENU',

    SEARCH_RESULTS: 'SEARCH_RESULTS',
    CARD: 'CARD',

    SETTINGS_ROOT: 'SETTINGS_ROOT',

    SETTINGS_SALARY: 'SETTINGS_SALARY',
    SETTINGS_CITY: 'SETTINGS_CITY',
    SETTINGS_SPECIALIZATION: 'SETTINGS_SPECIALIZATION',
    SETTINGS_GENDER: 'SETTINGS_GENDER',
    SETTINGS_SORTING: 'SETTINGS_SORTING',
};

export default STATES;